### ISSUE TITLE
No such file or directory when running zola within the container

### ISSUE THREAD

**Issue by jtmiclat** [j1mc/docker-zola#3]
Hello,

I am having problems running zola from within the container

```
$ docker run -it j1mc/docker-zola bash
bash-4.4# ./opt/zola-v0.6.0/zola 
bash: /opt/zola-v0.6.0/zola: No such file or directory
```

I am wondering if I am the only one facing this problem?

My hunch is that zola has some dependencies to link up the executable.

**Comment by jtmiclat** [comment]
There is an issue posted in zola repo.  https://github.com/getzola/zola/issues/553

**Comment by j1mc** [comment]
Hi - I'll take a look at this and will see what the issue is. I'll be in touch in the next few days.

**Comment by j1mc** [comment]
I've spent a good deal of time on this today --- sorry I can't come to a resolution on it. It does look like that upstream / zola project bug is impacting the ability to run this in a container.

**Comment by leiserfg** [comment]
I think that the image is not working well (probably because the image is based on alpine and zola requires glib).
Try with this one https://hub.docker.com/r/leiserfg/zola.

**Comment by j1mc** [comment]
@leiserfg - do you have a link to the git repository with the docker file?

**Comment by leiserfg** [comment]
There is not dockerfile, I'm just running 
`dockerize -t zola  /usr/bin/zola`

**Comment by leiserfg** [comment]
You need `pip install dockerize` first.

**Comment by jtmiclat** [comment]
I got it to work by using debian as the base and not alpine
Example Dockerfile:

```
FROM debian:stretch-slim
MAINTAINER Jim Campbell <jwcampbell@gmail.com>

ENV VERSION v0.6.0

WORKDIR /opt/zola
RUN apt-get update
RUN apt-get install bash curl tar -y
RUN curl -sL https://github.com/getzola/zola/releases/download/${VERSION}/zola-${VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar xvfz - -C /opt/zola

ENV PATH $PATH:/opt/zola
RUN rm -rf /var/lib/apt/lists/*
EXPOSE 1111

CMD ["zola serve"]

```

Testing the binary works:
```
$ docker build -q -t test_zola .
$ docker run test_zola zola --help
zola 0.6.0
Vincent Prouillet <prouillet.vincent@gmail.com>
A fast static site generator with everything built-in

USAGE:
    zola [OPTIONS] <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -c, --config <config>    Path to a config file other than config.toml [default: config.toml]

SUBCOMMANDS:
    build    Deletes the output directory if there is one and builds the site
    help     Prints this message or the help of the given subcommand(s)
    init     Create a new Zola project
    serve    Serve the site. Rebuild and reload on change automatically

```
End result creates bigger image

```
REPOSITORY            TAG                 IMAGE ID            CREATED              SIZE
test_zola             latest              65c57e11f5d5        About a minute ago   112MB
j1mc/docker-zola      latest              d018e1f59f38        47 hours ago         32.7MB
```

**Comment by leiserfg** [comment]
My version is baseless, just 38M.

**Comment by j1mc** [comment]
I prefer to have an actual docker file so that people know / can see what they're getting. The larger image size isn't a huge deal for me ... if others want to maintain a smaller image, I can definitely link to their setup in the README of this project.

I may have time to get to this tonight, but it may be tomorrow night.

**Comment by leiserfg** [comment]
True, I'll write a Dockerfile then.

**Comment by leiserfg** [comment]
https://github.com/leiserfg/docker-zola

**Comment by j1mc** [comment]
Thanks, @leiserfg ... i kind of feel like the project should have a proper docker file as part of its deployment. if you'd like to push that forward w/ the project maintainer, i'd be willing to support you in that.

otherwise, i think it would be good if only one of us maintained a docker file image ... i could either point my repo to your repo (via a readme w/ a link) or you could submit your changes here / i could add you as a collaborator.  either is okay with me, i'd just rather we not duplicate our efforts.

thanks for doing the work on this.

**Comment by leiserfg** [comment]
I will make a PR with my Dockerfile.

**Comment by j1mc** [comment]
Thanks, @leiserfg !!  : )
